const PRODUCTS_URL="data/produits.json";let products=[];let cart=JSON.parse(localStorage.getItem("boutique_cart")||"[]");

function money(v){return Number(v).toFixed(2).replace(".",",")+" €"}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function save(){localStorage.setItem("boutique_cart",JSON.stringify(cart));updateCount()}
function updateCount(){document.querySelectorAll("#cart-count").forEach(e=>e.textContent=cart.length)}
function card(p){return `<article class="product"><a class="product-img" href="produit.html?id=${p.id}">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.nom)}" onerror="this.remove();this.parentElement.innerHTML='<div class=\'placeholder\'>🛍️</div>'">`:`<div class="placeholder">🛍️</div>`}</a><div class="product-info"><div class="category">${esc(p.categorie)}</div><h3>${esc(p.nom)}</h3><p class="muted">${esc(p.description)}</p><div class="product-bottom"><span class="price">${money(p.prix)}</span><button class="btn primary small" onclick="add(${p.id})">Ajouter</button></div></div></article>`}
function render(list,id){const e=document.getElementById(id);if(e)e.innerHTML=list.map(card).join("")||"<div class='form'><h2>Aucun produit trouvé</h2></div>"}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;cart.push(p);save();alert(p.nom+" a été ajouté au panier.")}
function renderDetail(){const e=document.getElementById("product-detail");if(!e)return;const id=Number(new URLSearchParams(location.search).get("id"));const p=products.find(x=>x.id===id);if(!p){e.innerHTML="<div class='form'><h2>Produit introuvable</h2></div>";return}e.innerHTML=`<div class="detail"><div class="detail-img">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.nom)}">`:"<div class='placeholder'>🛍️</div>"}</div><div><div class="category">${esc(p.categorie)}</div><h1>${esc(p.nom)}</h1><div class="price">${money(p.prix)}</div><p class="muted">${esc(p.description)}</p><br><button class="btn primary" onclick="add(${p.id})">🛒 Ajouter au panier</button></div></div>`}
function renderCart(){const e=document.getElementById("cart-container");if(!e)return;if(!cart.length){e.innerHTML="<div class='form'><h2>Votre panier est vide.</h2><a class='btn primary' href='produits.html'>Voir les produits</a></div>";document.getElementById("cart-total").textContent=money(0);return}e.innerHTML=cart.map((p,i)=>`<div class="cart-item"><div><b>${esc(p.nom)}</b><div class="price">${money(p.prix)}</div></div><button class="remove" onclick="removeCart(${i})">Supprimer</button></div>`).join("");document.getElementById("cart-total").textContent=money(cart.reduce((s,p)=>s+Number(p.prix),0))}
function removeCart(i){cart.splice(i,1);save();renderCart()}
async function init(){updateCount();const m=document.getElementById("menu"),n=document.getElementById("nav");if(m&&n)m.onclick=()=>n.classList.toggle("open");try{const r=await fetch(PRODUCTS_URL);products=await r.json();render(products.slice(0,4),"home-products");render(products,"products-container");renderDetail();const search=document.getElementById("search");if(search)search.oninput=()=>render(products.filter(p=>(p.nom+" "+p.categorie).toLowerCase().includes(search.value.toLowerCase())),"products-container")}catch(e){console.error(e)}renderCart()}
document.addEventListener("DOMContentLoaded",init);
document.addEventListener("submit",e=>{if(["checkout","contact-form","login-form","register-form"].includes(e.target.id)){e.preventDefault();alert("Formulaire de démonstration. Le traitement réel sera connecté au backend.");}});
